services:
  - type: web
    name: btm-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: RPC_URL
        value: https://testnet-rpc.monad.xyz
      - key: PORT
        value: 3001
