# Exported from Render on 2025-04-06T20:06:20Z
services:
- type: web
  name: btm-api
  runtime: rust
  repo: https://github.com/Satoshixdreams/btm-api
  plan: free
  region: oregon
  buildCommand: cargo build --release
  startCommand: .
- type: web
  name: btm-api
  env: node
  buildCommand: npm install
  startCommand: npm start
  envVars:
    - key: RPC_URL
      value: https://testnet-rpc.monad.xyz
    - key: PORT
      fromService:
        type: web
        name: btm-api
        envVarKey: PORT
version: "1"
